name: tazavec
description: "Tazavec offers a fun way to break the ice and start meaningful conversations."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+8

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  groq_sdk:
    git:
      url: https://github.com/BranislavMateas/groq-dart-sdk.git

  loggy: ^2.0.3
  google_mobile_ads: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  device_info_plus: ^10.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
